name: Generate index.md
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
 
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: run generate.py
       run: |
         cd ./information-page/ && python ./generate.py
         git diff
         git config --global user.email "gu18647403665@outlook.com"
         git config --global user.name "Gayloc"
         git add ./index.md
         git commit -m "Github Action Auto Updated"
         git push
         
