name: Generate index.md
on:
  push:
    branches:
      - master

  schedule:
  - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
     - name: run generate.py
       run:
         python information-page/generate.py
